"""empty message

Revision ID: 6ac4e8fe4c44
Revises: None
Create Date: 2016-09-03 20:53:45.198768

"""

# revision identifiers, used by Alembic.
revision = '6ac4e8fe4c44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet')
    ### end Alembic commands ###
